config/routes.rb
Asistomatic::Application.routes.draw do

  get "inasistencias/new"

  get "inasistencias/show"

  get "bloques/index"

  get "bloques/show"

  get "bloques/new"

  get "bloques/create"

  get "bloques/edit"

  get "bloques/destroy"

  get "docentes/show"

  get "docentes/new"

  get "docentes/edit"

  get "docentes/delete"

  get "pages/index"

  root :to => "pages#home", :as => 'home'

  match "pages/home" => "pages#home"

  match 'docentes/index' => 'docentes#index', :as => 'docentes_index'
  match 'docentes/show' => 'docentes#show', :as => 'show'
  match 'docentes/new' => 'docentes#new', :as => 'new'
  match 'docentes/destroy' => 'docentes#destroy', :as => 'destroy'
  resources :docentes

  match '/bloques/index' => 'bloques#index', :as => 'bloques_index'
  match '/bloques/show' => 'bloques#show', :as => 'bloques_show'
  match '/bloques/new_option' => 'bloques#new_option', :as => 'bloques_new_option'
  match '/bloques/new_individual' => 'bloques#new_individual', :as => 'bloques_new_individual'
  match '/bloques/new_varios' => 'bloques#new_varios', :as => 'bloques_new_varios'
  match '/bloques/destroy' => 'bloques#destroy', :as => 'destroy'

  match '/inasistencias/index' => 'inasistencias#index', :as => 'inasistencia_index'
  match '/inasistencias/create' => 'inasistencias#create', :as => 'inasistencia_create'
  match '/inasistencias/destroy' => 'inasistencias#destroy', :as => 'inasistencias_destroy'

end

app/models/bloque.rb
# == Schema Information
# Schema version: 20110703170013
#
# Table name: bloques
#
#  id         :integer(4)      not null, primary key
#  numero     :integer(4)
#  hora_ini   :time
#  hora_fin   :time
#  created_at :datetime
#  updated_at :datetime
#  fecha_id   :integer(4)
#



class Bloque < ActiveRecord::Base

  attr_accessible :numero, :hora_ini, :hora_fin

  belongs_to :fecha

  validates :numero,  :presence   => true,
                      :uniqueness => true,
                      :numericality => { :greater_than => 0, :only_integer => true } 
                 
 
  validates :hora_ini, :presence => true
  validates :hora_fin, :presence => true



end

app/controllers/bloques_controller.rb
class BloquesController < ApplicationController

  def index
    @bloques = Bloque.all
  end

  def show
    #render :layout => false
  end

  def new_option
    
  end

  def new_individual
    @bloque = Bloque.new
    max_hora = 20
    hora = 7
    min = 0
    min_str = "00"
    @horas = []
    while hora < max_hora
      if min == 0 then 
        @horas.push("#{hora}:#{min_str}")
      else
        @horas.push("#{hora}:#{min}")
      end
      min += 45
      if (min >= 60)
        then  min = min - 60
              hora += 1
      else 
        end
    end
    render :new_individual, :layout => false
  end



  def new_varios
    @bloque = Bloque.new
    max_hora = 20
    hora = 7
    min = 0
    min_str = "00"
    @horas = []
    @intervalos = ["15 min.", "30 min.", "45 min.", "1 hr.", "1:15 hr.", "1:30 hr.", "1:45 hr.", "2 hr."]
    while hora < max_hora
      if min == 0 then 
        @horas.push("#{hora}:#{min_str}")
      else
        @horas.push("#{hora}:#{min}")
      end
      min += 45
      if (min >= 60)
        then  min = min - 60
              hora += 1
      else 
        end
    end
    render :new_varios, :layout => false
  end


  def create
    @bloque = Bloque.new(:params[:bloque])
  end

  def edit
  end

  def destroy
  end

end

app/helpers/bloques_helper.rb
module BloquesHelper
end

app/views/bloques/_test.html.erb
Hola

app/views/bloques/create.html.erb
<h1>Bloques#create</h1>
<p>dsfdsfFind me in app/views/bloques/create.html.erb</p>

app/views/bloques/destroy.html.erb
<h1>Bloques#destroy</h1>
<p>Find me in app/views/bloques/destroy.html.erb</p>

app/views/bloques/edit.html.erb
<h1>Bloques#edit</h1>
<p>Find me in app/views/bloques/edit.html.erb</p>

app/views/bloques/index.html.erb
<h1>Bloques de Horario</h1>

<p><%= link_to "Agregar nuevo bloque", bloques_new_option_path %></p>

app/views/bloques/new.html.erb
<h1>Agregar nuevo bloque de horario</h1>


<table>

    <%= form_for(@bloque) do |f| %>

      <div class="field">
        <tr>
          <td><%= f.label "Número de Bloque" %></td><td><%= f.text_field :numero, :type => 'number', :size => 3, :maximum_length => 3 %></br>
          </td>
        </tr>
      </div>

      <div class="field">
        <tr><td><%= f.label "Hora inicial" %></td><td><%= f.select :hora_ini, options_for_select(@horas) %></br></td>
      </div>
      <div class="field">
        <td><td><%= f.label "Hora final" %></td><td><%= f.select :hora_fin, options_for_select(@horas) %></br></td></tr>
      </div>

      <div class="field">
        <tr><td><%= f.label "Fecha inicial" %></td><td><%= text_field_tag "datepicker_ini", '', :size => 8 %></br></td>
      </div>
      <div class="field">
        <td><%= f.label "Fecha final" %></td><td><%= text_field_tag "datepicker_fin", '', :size => 8 %></td></br>
      </tr>
      </div>

      <div class="field">
        <tr><td><%= f.label "Incluir sábados" %></td><td><%= check_box_tag 'incluir_sab' %></td></br>
      </div>
      <div class="field">
        <td><%= f.label "Incluir domingos" %></td><td><%= check_box_tag 'incluir_dom' %></br></tr>
      </div>


      <div class="actions">
        <tr><td colspan=4 ><%= f.submit 'Agregar' %></td></tr>
      </div>
    <% end %>

</table>

<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('#datepicker_ini').datepicker();
    $('#datepicker_fin').datepicker();
  });
</script>

app/views/bloques/new_individual.html.erb
<table>

    <%= form_for :bloque do |f| %>

      <div class="field">
        <tr>
          <td><%= f.label "Número de Bloque" %></td><td><%= f.text_field :numero, :type => 'number', :size => 3, :maximum_length => 3 %></br>
          </td>
        </tr>
      </div>

      <div class="field">
        <tr><td><%= f.label "Hora inicial" %></td><td><%= f.select :hora_ini, options_for_select(@horas) %></br></td>
      </div>
      <div class="field">
        <td><%= f.label "Hora final" %></td><td><%= f.select :hora_fin, options_for_select(@horas) %></br></td>
      </div>

      <div class="field">
        <tr><td><%= f.label "Fecha inicial" %></td><td><%= text_field_tag "datepicker_ini", '', :size => 8 %></br></td>
      </div>
      <div class="field">
        <td><%= f.label "Fecha final" %></td><td><%= text_field_tag "datepicker_fin", '', :size => 8 %></br></tr></td>
      </div>


      <div class="field">
        <tr><td><%= f.label "Incluir sábados" %></td><td><%= check_box_tag 'incluir_sab' %></td></br>
      </div>
      <div class="field">
        <td><%= f.label "Incluir domingos" %></td><td><%= check_box_tag 'incluir_dom' %></br></tr>
      </div>


      <div class="actions">
        <tr><td colspan=4 ><%= f.submit 'Agregar' %></td></tr>
      </div>
    <% end %>

</table>

<script type="text/javascript">
  jQuery(function($) {
    $("#datepicker_ini").datepicker();
    $("#datepicker_fin").datepicker();
  });
</script>

app/views/bloques/new_option.html.erb
<h1>Agregar nuevo bloque de horario</h1>


    <%= form_tag 'radio', :remote => true do %>
      <div class="field">
        <tr>
          <td><%= label_tag "Elegir tipo de creación de bloques" %></td>
          <td>Un bloque por día<%= radio_button_tag 'tipo_creacion', 'individual' %></br></td>
          <td>Varios bloques por día<%= radio_button_tag 'tipo_creacion', 'varios' %></br></td>
          
        </tr>
      </div>

    <% end %>

  <div id="bloques_new"/>

<script type="text/javascript">
  jQuery(function($) {
    $("#tipo_creacion_individual").change(function() {
      $.post("/bloques/new_individual", function(data) {
        $("#bloques_new").html(data);
      })
    });      
    $("#tipo_creacion_varios").change(function() {
      $.post("/bloques/new_varios", function(data) {
        $("#bloques_new").html(data);
      })
    });      

  });
</script>

app/views/bloques/new_varios.html.erb
<table>

    <%= form_for :bloque do |f| %>

      <div class="field">
        <tr>
          <td><%= f.label "Número de Bloque" %></td><td><%= f.text_field :numero, :type => 'number', :size => 3, :maximum_length => 3 %></br>
          </td>
        </tr>
      </div>

      <div class="field">
        <tr><td><%= f.label "Hora inicial" %></td><td><%= f.select :hora_ini, options_for_select(@horas) %></br></td>
      </div>
      <div class="field">
        <td><%= f.label "Hora final" %></td><td><%= f.select :hora_fin, options_for_select(@horas) %></br></td>
      </div>

      <div class="field">
        <td><%= f.label "Intervalos" %></td><td><%= select 'intervalo', '', options_for_select(@intervalos) %></br></td></tr>
      </div>


      <div class="field">
        <tr><td><%= f.label "Fecha inicial" %></td><td><%= text_field_tag "datepicker_ini", '', :size => 8 %></br></td>
      </div>
      <div class="field">
        <td><%= f.label "Fecha final" %></td><td><%= text_field_tag "datepicker_fin", '', :size => 8 %></td></br>
      </tr>
      </div>

      <div class="field">
        <tr><td><%= f.label "Incluir sábados" %></td><td><%= check_box_tag 'incluir_sab' %></td></br>
      </div>
      <div class="field">
        <td><%= f.label "Incluir domingos" %></td><td><%= check_box_tag 'incluir_dom' %></br></tr>
      </div>


      <div class="actions">
        <tr><td colspan=4 ><%= f.submit 'Agregar' %></td></tr>
      </div>
    <% end %>

</table>

<script type="text/javascript">
  jQuery(function($) {
    $("#datepicker_ini").datepicker();
    $("#datepicker_fin").datepicker();
  });
</script>

app/views/bloques/show.html.erb
<h1>Bloques#show</h1>
<p>fdfdfdFind me in app/views/bloques/show.html.erb</p>