config/routes.rb
Asistomatic::Application.routes.draw do

  get "inasistencias/new"

  get "inasistencias/show"

  get "bloques/index"

  get "bloques/show"

  get "bloques/new"

  get "bloques/create"

  get "bloques/edit"

  get "bloques/destroy"

  get "docentes/show"

  get "docentes/new"

  get "docentes/edit"

  get "docentes/delete"

  get "pages/index"

  root :to => "pages#home", :as => 'home'

  match "pages/home" => "pages#home"

  match 'docentes/index' => 'docentes#index', :as => 'docentes_index'
  match 'docentes/show' => 'docentes#show', :as => 'show'
  match 'docentes/new' => 'docentes#new', :as => 'new'
  match 'docentes/destroy' => 'docentes#destroy', :as => 'destroy'
  resources :docentes

  match '/bloques/index' => 'bloques#index', :as => 'bloques_index'
  match '/bloques/show' => 'bloques#show', :as => 'bloques_show'
  match '/bloques/new_option' => 'bloques#new_option', :as => 'bloques_new_option'
  match '/bloques/new_individual' => 'bloques#new_individual', :as => 'bloques_new_individual'
  match '/bloques/new_varios' => 'bloques#new_varios', :as => 'bloques_new_varios'
  match '/bloques/destroy' => 'bloques#destroy', :as => 'destroy'

  match '/inasistencias/index' => 'inasistencias#index', :as => 'inasistencia_index'
  match '/inasistencias/create' => 'inasistencias#create', :as => 'inasistencia_create'
  match '/inasistencias/destroy' => 'inasistencias#destroy', :as => 'inasistencias_destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asistomatic</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery-ui-1.8.13.custom.min" %>
  <%= csrf_meta_tag %>
</head>
<body>


<div id="wrapper"><!-- #wrapper -->

	<header><!-- header -->
		<h1><a href="#">ASISTOMATIC</a></h1>
		<h2>Sistema de Asistencia Automatizado</h2>
	</header><!-- end of header -->
	
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><a href="#">Página Inicial</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Products</a></li>
				<li><a href="#">Services</a></li>
				<li><a href="#">Ayuda</a></li>
				<li><a href="#">Contact Us</a></li>
			</ul>
		</div>
	</nav><!-- end of top nav -->
	
	<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- #content -->
			
			<%= yield %>
						
			</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Administración</h3>
					<ul>
                                          <li><%= link_to "Docentes", docentes_index_path %></li>
                                          <li><%= link_to "Bloques de Horario", bloques_index_path %></li>
					</ul>
					
				<h3>Sponsors</h3>
					<img src="images/ad125.jpg" alt="" /><br /><img src="images/ad125.jpg" alt="" /><br /><br />

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
	
		<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Friends</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside class="footer-segment">
							<h4>Awesome Stuff</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside class="footer-segment">
							<h4>Coolness</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside class="footer-segment">
							<h4>Blahdyblah</h4>
								<p>&copy; 2010 <a href="#">yoursite.com</a> Praesent libero. Sed cursus ante dapibus diam. Sed nisi.</p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>
	
</div><!-- #wrapper -->



</body>
</html>